# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: Static analysis

on:
  pull_request:
    paths:
      - 'lib/**'
      - 'templates/**'
      - 'tests/**'
      - 'vendor/**'
      - 'vendor-bin/**'
      - composer.lock
  push:
    branches:
      - master
      - main
      - stable*

concurrency:
  group: psalm-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '8.1', '8.2', '8.3' ]
        server-versions: [ 'dev-master' ]
      fail-fast: false

    name: Nextcloud
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up php
        uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d # v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          composer require --with-all-dependencies nextcloud/ocp:${{ matrix.server-versions }}

      - name: Run coding standards check
        run: composer run psalm
